### ISSUE TITLE
Privacy add-on blocking API docs from loading

### ISSUE THREAD

**Issue by OmgImAlexis** [saasify-sh/saasify#19] opened 2019-10-25 02:00 UTC
Page: https://puppet-master.sh/docs

I'm running a few privacy addons and one of them blocked the API by default. Issues with the page are to be expected but I didn't expect the whole page to crash like this.

In production maybe this should default to a nicer more end user friendly version.

```
Error downloading https://api.saasify.sh/1/deployments/openapi/transitive-bullshit/puppet-master@a818aeac Failed to fetch
Stack trace
Error: Error downloading https://api.saasify.sh/1/deployments/openapi/transitive-bullshit/puppet-master@a818aeac 
Failed to fetch
    at https://puppet-master.sh/static/js/3.cc3278d9.chunk.js:1:23110
    at https://puppet-master.sh/static/js/3.cc3278d9.chunk.js:1:922267

TypeError: Failed to fetch

ReDoc Version: 2.0.0-rc.14
Commit: 121bf64
```

**Comment by transitive-bullshit** [comment] 2019-10-25 02:07
Interesting -- definitely agreed that we should handle this more gracefully.

Any idea what about that relatively standard `JSON` GET request triggered the privacy add-on to block it?

Also, I'm curious which privacy add-on(s) you're using since this may be something other people run into and want to search for.

Thanks for the head's up!

**Comment by transitive-bullshit** [comment] 2019-10-25 02:59
I updated the SaaS client website to handle these types of errors gracefully now, instead falling back to a more descriptive error page.

Would still love to figure out what was triggering the privacy add-on since afaict that `GET` call is fairly innocuous.

Thanks again!

**Comment by OmgImAlexis** [comment] 2019-10-25 05:16
You managed to trip up safe-script, uBlock and Privacy Badger.

I have my settings really high so it's unlikely to happen to a lot of users.

**Comment by transitive-bullshit** [comment] 2019-10-25 05:49
Sounds good -- closing for now, but will investigate further to repro and figure out the root cause.

**Closed by transitive-bullshit** 2019-10-25 05:49 UTC
